name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment (thay đổi nếu bạn dùng ngôn ngữ khác)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm test

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'  # Chỉ triển khai trên nhánh main

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Run deployment script
      - name: Deploy Application
        run: |
          echo "Deploying application..."
          # Thêm lệnh triển khai thực tế tại đây, ví dụ: ssh hoặc CLI của cloud provider.
