name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Send success notification
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{"content": "✅ Deployment succeeded! Check your app now!"}' \
           https://discord.com/api/webhooks/1326616309609529404/jW9CVDmaXlCDpbOdtyCMXd3NoxHsp2iME6mJSRLa65j_TYigPbniqqo7a5HrGngD-EUj

      - name: Send failure notification
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{"content": "❌ Deployment failed! Please check the logs for details."}' \
            https://discord.com/api/webhooks/1326616309609529404/jW9CVDmaXlCDpbOdtyCMXd3NoxHsp2iME6mJSRLa65j_TYigPbniqqo7a5HrGngD-EUj
