name: CI & CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


  
      - name: Install dependencies
        run: |
          npm install
          npm install -g expo-cli

     

      - name: Build and Publish App to Expo
        run: expo publish --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
