name: CI & CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
    

  
      - name: Install dependencies
        run: |
          npm install
          npm install -g expo-cli

      - name: Log in to Expo
        run: echo "$EXPO_TOKEN" | expo login --non-interactive --username $EXPO_USERNAME --password $EXPO_PASSWORD

      - name: Build and Publish App to Expo
        run: expo publish --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
