name: Scheduled Workflow

on:
  schedule:
    # Cron job chạy lúc 12:00 trưa mỗi ngày
    - cron: '0 12 * * *'  # Chạy lúc 12:00 trưa mỗi ngày
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print message
        run: echo "Hello from scheduled workflow!"
