name: Sample Workflow

on:
  workflow_dispatch: # Chỉ cho phép chạy thủ công

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print message
        run: echo "Hello from manually triggered workflow!"
