name: Health Check

on:
  schedule:
    - cron: '0 0 * * *' # Chạy mỗi ngày vào lúc 00:00 UTC
  workflow_dispatch: # Chạy thủ công khi cần

jobs:
  health-check:
    runs-on: ubuntu-latest

    steps:
      - name: Health check request
        uses: jakejarvis/url-health-check@v1
        with:
          url: 'https://ba0f-31-216-224-152.ngrok-free.app/health'  # Thay thế bằng URL thực của bạn
