on:
  schedule:
    - cron: '5 10 * * *' # Chạy lúc 10:05 sáng hàng ngày

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run script
        run: echo "Hello from my scheduled job!"
